export type RiskLevel = "BAJO" | "MEDIO" | "ALTO";

export type UserMode = "citizen" | "journalist" | "official";

export type CompanySearchResult = {
  ruc: string;
  razonSocial: string;
  region: string;
  province: string;
  district: string;
};

export type CompanySearchResponse = {
  data: CompanySearchResult[];
};

export type Summary = {
  riskLevel: RiskLevel;
  riskScore: number;
  lastSyncedAt: string | null;
};

export type Safety = {
  fatalAccidents: number;
  occupationalDiseases: number;
  source: string;
};

export type EnvironmentalSanction = {
  authority: string;
  date: string;
  description: string;
  amount: number | null;
};

export type AirQualityRecord = {
  stationName: string;
  year: number;
  parameter: string;
  value: number;
  unit: string;
};

export type Environmental = {
  sanctionsCount: number;
  sanctions: EnvironmentalSanction[];
  airQuality: AirQualityRecord[];
};

export type LegalSanction = {
  authority: string;
  date: string;
  description: string;
};

export type LegalFine = {
  authority: string;
  date: string;
  amount: number;
  currency: string;
};

export type Tender = {
  code: string;
  title: string;
  date: string;
  amount: number | null;
  currency: string | null;
};

export type Legal = {
  osceSanctions: LegalSanction[];
  osceFines: LegalFine[];
  tenders: Tender[];
  sunatStatus?: string;
  sunatCondition?: string;
  sunatAddress?: string;
  sunatLocales?: Array<{ ubigeo: string; lugar: string; direccion: string }>;
  sunatDebts?: Array<{ amount: number; status: string; authority: string; resolutionsCount: number }>;
};

export type SocialConflict = {
  region: string;
  province: string;
  district: string;
  description: string;
  status: string;
  reportedAt: string;
};

export type Social = {
  activeConflicts: number;
  conflicts: SocialConflict[];
};

export type PublicProject = {
  name: string;
  budget: number;
  physicalProgress: number;
  executor: string;
};

export type Investment = {
  publicProjects: PublicProject[];
  totalBudget: number;
};

export type MiningProjectStatus =
  | "de_acuerdo"
  | "paralizado"
  | "en_tramite"
  | "cerrado";

export type MiningProject = {
  id: string;
  name: string;
  status: MiningProjectStatus;
  location: string;
  process: string;
  mineralType: string;
  estimatedMonthsRemaining: number | null;
};

export type RegularizationStatus =
  | "sin_tramite"
  | "en_tramite"
  | "regularizado"
  | "desestimado";

export type IllegalMiningRecord = {
  id: string;
  location: string;
  reason: string;
  regularizationStatus: RegularizationStatus;
  detectedAt?: string | null;
};

export type CompanyDashboard = {
  ruc: string;
  razonSocial: string;
  summary: Summary;
  safety: Safety;
  environmental: Environmental;
  legal: Legal;
  social: Social;
  investment: Investment;
  miningProjects: MiningProject[];
  illegalMining: IllegalMiningRecord[];
};

export type RegionCompany = {
  ruc: string;
  razonSocial: string;
  latitude: number;
  longitude: number;
  riskLevel: RiskLevel;
};

export type RegionConflict = {
  description: string;
  latitude: number;
  longitude: number;
  status: string;
};

export type RegionProject = {
  name: string;
  budget: number;
  latitude: number;
  longitude: number;
};

export type RegionSummary = {
  region: string;
  companies: RegionCompany[];
  conflicts: RegionConflict[];
  projects: RegionProject[];
  miningProjects: MiningProject[];
  illegalMining: IllegalMiningRecord[];
};

// Aliases for frontend components generated by Kombai
export type CompanySearchData = CompanySearchResult;
export type CompanyDashboardData = CompanyDashboard;
export type RegionResponse = RegionSummary;
export type ProjectStatus = MiningProjectStatus;
